- hosts: mngsrv
  remote_user: vagrant
  become: yes
  tasks:
    - name: Run the Docker installation script
      shell: /bin/curl -fsSL https://get.docker.com/ | sh

    - name: Start the Docker daemon
      command: /sbin/service docker start

    - name: Add "vagrant" to "docker" group
      command: /sbin/usermod -aG docker vagrant

    - name: Ensure Docker starts when system booting
      command: /sbin/chkconfig docker on

    - name: Run redmine simply
      command: /bin/docker run -d -p 3000:3000 --name some-redmine redmine

- hosts: dbgsrv
  remote_user: vagrant
  become: yes
  tasks:
    - name: Upate packages
      apt: upgrade=dist

    - name: Install build-essential package
      apt: name=build-essential state=latest

- hosts: devsrv
  remote_user: vagrant
  tasks:
    - name: Upate packages
      apt: upgrade=dist
      become: yes

    - name: Download Go compiler binary
      command: /usr/bin/wget https://storage.googleapis.com/golang/go1.4.linux-amd64.tar.gz

    - name: Extract Go compiler
      command: /bin/tar zxvf go1.4.linux-amd64.tar.gz

    - name: Rename folder name
      command: /bin/mv ./go ./go1.4

    - name: Install Git
      apt: name=git state=latest
      become: yes

    - name: Create a working directory
      file: path=/home/vagrant/work state=directory

    - name: Fetch Go lang repository
      command: /usr/bin/git clone https://go.googlesource.com/go chdir=/home/vagrant/work/

    - name: Build Go binary
      command: ./all.bash chdir=work/go/src/

    - name: Set environment variable [GOROOT]
      shell: echo "export GOROOT=$HOME/work/go" >> ~/.bashrc

    - name: Add $GOPATH/bin to PATH
      shell: echo "export PATH=$PATH:$GOROOT/bin" >> ~/.bashrc

    - name: Reflect $GOPATH
      shell: source ~/.bashrc executable=/bin/bash

